spring.application.name=BankProject
spring.datasource.url=jdbc:mysql://localhost:3307/bank_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=harsha
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true